AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExtractToken:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/ExtractToken/
      Handler: bootstrap
      Runtime: dotnet8
      Environment:
        Variables:
          MONGODB_URI: "mongodb://username:password@http://127.0.0.1:27017/MfaDataStore" 

  GetToken:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/GetToken/
      Handler: bootstrap        
      Runtime: dotnet8
      Environment:
        Variables:
          MONGODB_URI: "mongodb://username:password@http://127.0.0.1:27017/MfaDataStore" 
      Events:
        GetTokenApi:
          Type: Api
          Properties:
            Path: /get-token
            Method: get
            RestApiId:
              Ref: APIResource

  APIResource:
    Type: AWS::Serverless::Api
    Properties:
      Name: APIResourceGateway
      StageName: dev
